Update GitUtils add methods from studio and deployer
craftercms/commons pull request #304
Opened 2022-05-25 10:05 UTC by phuongnq

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/5600

2022-05-25 21:01 UTC, jdrossl approved these changes

2022-06-01 14:26 UTC, avasquez614 requested changes

2022-06-01 14:26 UTC, avasquez614 commented on git/src/main/java/org/craftercms/commons/git/utils/GitUtils.java
> +    public static void unlock(String repoPath) throws IOException {
Please add Javadoc comments

2022-06-01 14:26 UTC, avasquez614 commented on git/src/main/java/org/craftercms/commons/git/utils/GitUtils.java
> +    public static void deleteGitIndex(String repoPath) throws IOException {
Please add Javadoc comments

2022-06-01 19:43 UTC, avasquez614 approved these changes

2022-06-01 19:47 UTC, merged